insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,1,'Acre','AC');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,2,'Alagoas','AL');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,3,'Amazonas','AM');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,4,'Amapá','AP');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,5,'Bahia','BA');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,6,'Ceará','CE');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,7,'Distrito Federal','DF');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,8,'Espírito Santo','ES');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,9,'Goiás','GO');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,10,'Maranhão','MA');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,11,'Minas Gerais','MG');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,12,'Mato Grosso do Sul','MS');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,13,'Mato Grosso','MT');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,14,'Pará','PA');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,15,'Paraiba','PB');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,16,'Pernambuco','PE');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,17,'Piauí','PI');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,18,'Paraná','PR');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,19,'Rio de Janeiro','RJ');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,20,'Rio Grande do Norte','RN');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,21,'Rondônia','RO');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,22,'Roraima','RR');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,23,'Rio Grande do Sul','RS');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,24,'Santa Catarina','SC');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,25,'Sergipe','SE');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,26,'São Paulo','SP');
insert  into estado(cd_pais ,cd_estado, ds_estado, sg_estado) values (31,27,'Tocantins','TO');
