insert  into pais(cd_pais, nr_pais, ds_pais) values (1,'AD','Andorra');
insert  into pais(cd_pais, nr_pais, ds_pais) values (2,'AE','Emirados Árabes Unidos');
insert  into pais(cd_pais, nr_pais, ds_pais) values (3,'AF','Afeganistão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (4,'AG','Antígua e Barbuda');
insert  into pais(cd_pais, nr_pais, ds_pais) values (5,'AI','Anguilla');
insert  into pais(cd_pais, nr_pais, ds_pais) values (6,'AL','Albânia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (7,'AM','Armênia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (8,'AN','Antilhas Holandesas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (9,'AO','Angola');
insert  into pais(cd_pais, nr_pais, ds_pais) values (10,'AQ','Antártida');
insert  into pais(cd_pais, nr_pais, ds_pais) values (11,'AR','Argentina');
insert  into pais(cd_pais, nr_pais, ds_pais) values (12,'AS','Samoa Americana');
insert  into pais(cd_pais, nr_pais, ds_pais) values (13,'AT','Áustria');
insert  into pais(cd_pais, nr_pais, ds_pais) values (14,'AU','Austrália');
insert  into pais(cd_pais, nr_pais, ds_pais) values (15,'AW','Aruba');
insert  into pais(cd_pais, nr_pais, ds_pais) values (16,'AX','Ilhas Aland');
insert  into pais(cd_pais, nr_pais, ds_pais) values (17,'AZ','Azerbaijão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (18,'BA','Bósnia-Herzegovina');
insert  into pais(cd_pais, nr_pais, ds_pais) values (19,'BB','Barbados');
insert  into pais(cd_pais, nr_pais, ds_pais) values (20,'BD','Bangladesh');
insert  into pais(cd_pais, nr_pais, ds_pais) values (21,'BE','Bélgica');
insert  into pais(cd_pais, nr_pais, ds_pais) values (22,'BF','Burquina Faso');
insert  into pais(cd_pais, nr_pais, ds_pais) values (23,'BG','Bulgária');
insert  into pais(cd_pais, nr_pais, ds_pais) values (24,'BH','Bahrain');
insert  into pais(cd_pais, nr_pais, ds_pais) values (25,'BI','Burundi');
insert  into pais(cd_pais, nr_pais, ds_pais) values (26,'BJ','Benin');
insert  into pais(cd_pais, nr_pais, ds_pais) values (27,'BL','São Bartolomeu');
insert  into pais(cd_pais, nr_pais, ds_pais) values (28,'BM','Bermudas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (29,'BN','Brunei');
insert  into pais(cd_pais, nr_pais, ds_pais) values (30,'BO','Bolívia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (31,'BR','Brasil');
insert  into pais(cd_pais, nr_pais, ds_pais) values (32,'BS','Bahamas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (33,'BT','Butão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (34,'BV','Ilha Bouvet');
insert  into pais(cd_pais, nr_pais, ds_pais) values (35,'BW','Botsuana');
insert  into pais(cd_pais, nr_pais, ds_pais) values (36,'BY','Belarus');
insert  into pais(cd_pais, nr_pais, ds_pais) values (37,'BZ','Belize');
insert  into pais(cd_pais, nr_pais, ds_pais) values (38,'CA','Canadá');
insert  into pais(cd_pais, nr_pais, ds_pais) values (39,'CC','Ilhas Coco');
insert  into pais(cd_pais, nr_pais, ds_pais) values (40,'CD','Congo-Kinshasa');
insert  into pais(cd_pais, nr_pais, ds_pais) values (41,'CF','República Centro-Africana');
insert  into pais(cd_pais, nr_pais, ds_pais) values (42,'CG','Congo');
insert  into pais(cd_pais, nr_pais, ds_pais) values (43,'CH','Suíça');
insert  into pais(cd_pais, nr_pais, ds_pais) values (44,'CI','Costa do Marfim');
insert  into pais(cd_pais, nr_pais, ds_pais) values (45,'CK','Ilhas Cook');
insert  into pais(cd_pais, nr_pais, ds_pais) values (46,'CL','Chile');
insert  into pais(cd_pais, nr_pais, ds_pais) values (47,'CM','República dos Camarões');
insert  into pais(cd_pais, nr_pais, ds_pais) values (48,'CN','China');
insert  into pais(cd_pais, nr_pais, ds_pais) values (49,'CO','Colômbia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (50,'CR','Costa Rica');
insert  into pais(cd_pais, nr_pais, ds_pais) values (51,'CS','Sérvia e Montenegro');
insert  into pais(cd_pais, nr_pais, ds_pais) values (52,'CU','Cuba');
insert  into pais(cd_pais, nr_pais, ds_pais) values (53,'CV','Cabo Verde');
insert  into pais(cd_pais, nr_pais, ds_pais) values (54,'CX','Ilhas Natal');
insert  into pais(cd_pais, nr_pais, ds_pais) values (55,'CY','Chipre');
insert  into pais(cd_pais, nr_pais, ds_pais) values (56,'CZ','República Tcheca');
insert  into pais(cd_pais, nr_pais, ds_pais) values (57,'DE','Alemanha');
insert  into pais(cd_pais, nr_pais, ds_pais) values (58,'DJ','Djibuti');
insert  into pais(cd_pais, nr_pais, ds_pais) values (59,'DK','Dinamarca');
insert  into pais(cd_pais, nr_pais, ds_pais) values (60,'DM','Dominica');
insert  into pais(cd_pais, nr_pais, ds_pais) values (61,'DO','República Dominicana');
insert  into pais(cd_pais, nr_pais, ds_pais) values (62,'DZ','Argélia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (63,'EC','Equador');
insert  into pais(cd_pais, nr_pais, ds_pais) values (64,'EE','Estônia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (65,'EG','Egito');
insert  into pais(cd_pais, nr_pais, ds_pais) values (66,'EH','Saara Ocidental');
insert  into pais(cd_pais, nr_pais, ds_pais) values (67,'ER','Eritreia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (68,'ES','Espanha');
insert  into pais(cd_pais, nr_pais, ds_pais) values (69,'ET','Etiópia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (70,'FI','Finlândia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (71,'FJ','Fiji');
insert  into pais(cd_pais, nr_pais, ds_pais) values (72,'FK','Ilhas Malvinas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (73,'FM','Micronésia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (74,'FO','Ilhas Faroe');
insert  into pais(cd_pais, nr_pais, ds_pais) values (75,'FR','França');
insert  into pais(cd_pais, nr_pais, ds_pais) values (76,'GA','Gabão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (77,'GB','Reino Unido');
insert  into pais(cd_pais, nr_pais, ds_pais) values (78,'GD','Granada');
insert  into pais(cd_pais, nr_pais, ds_pais) values (79,'GE','Geórgia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (80,'GF','Guiana Francesa');
insert  into pais(cd_pais, nr_pais, ds_pais) values (81,'GG','Guernsey');
insert  into pais(cd_pais, nr_pais, ds_pais) values (82,'GH','Gana');
insert  into pais(cd_pais, nr_pais, ds_pais) values (83,'GI','Gibraltar');
insert  into pais(cd_pais, nr_pais, ds_pais) values (84,'GL','Groênlandia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (85,'GM','Gâmbia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (86,'GN','Guiné');
insert  into pais(cd_pais, nr_pais, ds_pais) values (87,'GP','Guadalupe');
insert  into pais(cd_pais, nr_pais, ds_pais) values (88,'GQ','Guiné Equatorial');
insert  into pais(cd_pais, nr_pais, ds_pais) values (89,'GR','Grécia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (90,'GS','Geórgia do Sul e Ilhas Sandwich do Sul');
insert  into pais(cd_pais, nr_pais, ds_pais) values (91,'GT','Guatemala');
insert  into pais(cd_pais, nr_pais, ds_pais) values (92,'GU','Guam');
insert  into pais(cd_pais, nr_pais, ds_pais) values (93,'GW','Guiné Bissau');
insert  into pais(cd_pais, nr_pais, ds_pais) values (94,'GY','Guiana');
insert  into pais(cd_pais, nr_pais, ds_pais) values (95,'HK','Hong Kong');
insert  into pais(cd_pais, nr_pais, ds_pais) values (96,'HM','Ilha Heard e Ilhas McDonald');
insert  into pais(cd_pais, nr_pais, ds_pais) values (97,'HN','Honduras');
insert  into pais(cd_pais, nr_pais, ds_pais) values (98,'HR','Croácia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (99,'HT','Haiti');
insert  into pais(cd_pais, nr_pais, ds_pais) values (100,'HU','Hungria');
insert  into pais(cd_pais, nr_pais, ds_pais) values (101,'ID','Indonésia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (102,'IE','Irlanda');
insert  into pais(cd_pais, nr_pais, ds_pais) values (103,'IL','Israel');
insert  into pais(cd_pais, nr_pais, ds_pais) values (104,'IM','Ilha de Man');
insert  into pais(cd_pais, nr_pais, ds_pais) values (105,'IN','Índia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (106,'IO','Território Britânico do Oceano Índico');
insert  into pais(cd_pais, nr_pais, ds_pais) values (107,'IQ','Iraque');
insert  into pais(cd_pais, nr_pais, ds_pais) values (108,'IR','Irã');
insert  into pais(cd_pais, nr_pais, ds_pais) values (109,'IS','Islândia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (110,'IT','Itália');
insert  into pais(cd_pais, nr_pais, ds_pais) values (111,'JE','Jersey');
insert  into pais(cd_pais, nr_pais, ds_pais) values (112,'JM','Jamaica');
insert  into pais(cd_pais, nr_pais, ds_pais) values (113,'JO','Jordânia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (114,'JP','Japão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (115,'KE','Quênia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (116,'KG','Quirguistão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (117,'KH','Camboja');
insert  into pais(cd_pais, nr_pais, ds_pais) values (118,'KI','Quiribati');
insert  into pais(cd_pais, nr_pais, ds_pais) values (119,'KM','Comores');
insert  into pais(cd_pais, nr_pais, ds_pais) values (120,'KN','São Cristovão e Nevis');
insert  into pais(cd_pais, nr_pais, ds_pais) values (121,'KP','Coreia do Norte');
insert  into pais(cd_pais, nr_pais, ds_pais) values (122,'KR','Coreia do Sul');
insert  into pais(cd_pais, nr_pais, ds_pais) values (123,'KW','Kuwait');
insert  into pais(cd_pais, nr_pais, ds_pais) values (124,'KY','Ilhas Caiman');
insert  into pais(cd_pais, nr_pais, ds_pais) values (125,'KZ','Casaquistão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (126,'LA','República Popular Democrática do Laos');
insert  into pais(cd_pais, nr_pais, ds_pais) values (127,'LB','Líbano');
insert  into pais(cd_pais, nr_pais, ds_pais) values (128,'LC','Santa Lúcia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (129,'LI','Liechtenstein');
insert  into pais(cd_pais, nr_pais, ds_pais) values (130,'LK','Sri Lanka');
insert  into pais(cd_pais, nr_pais, ds_pais) values (131,'LR','Libéria');
insert  into pais(cd_pais, nr_pais, ds_pais) values (132,'LS','Lesoto');
insert  into pais(cd_pais, nr_pais, ds_pais) values (133,'LT','Lituânia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (134,'LU','Luxemburgo');
insert  into pais(cd_pais, nr_pais, ds_pais) values (135,'LV','Letônia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (136,'LY','Líbia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (137,'MA','Marrocos');
insert  into pais(cd_pais, nr_pais, ds_pais) values (138,'MC','Mônaco');
insert  into pais(cd_pais, nr_pais, ds_pais) values (139,'MD','Moldávia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (140,'ME','Montenegro');
insert  into pais(cd_pais, nr_pais, ds_pais) values (141,'MF','São Martinho');
insert  into pais(cd_pais, nr_pais, ds_pais) values (142,'MG','Madagascar');
insert  into pais(cd_pais, nr_pais, ds_pais) values (143,'MH','Ilhas Marshall');
insert  into pais(cd_pais, nr_pais, ds_pais) values (144,'MK','Macedônia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (145,'ML','Mali');
insert  into pais(cd_pais, nr_pais, ds_pais) values (146,'MM','Mianmar');
insert  into pais(cd_pais, nr_pais, ds_pais) values (147,'MN','Mongólia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (148,'MO','Macau');
insert  into pais(cd_pais, nr_pais, ds_pais) values (149,'MP','Ilhas Marianas do Norte');
insert  into pais(cd_pais, nr_pais, ds_pais) values (150,'MQ','Martinica');
insert  into pais(cd_pais, nr_pais, ds_pais) values (151,'MR','Mauritânia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (152,'MS','Montserrat');
insert  into pais(cd_pais, nr_pais, ds_pais) values (153,'MT','Malta');
insert  into pais(cd_pais, nr_pais, ds_pais) values (154,'MU','Maurício');
insert  into pais(cd_pais, nr_pais, ds_pais) values (155,'MV','Maldivas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (156,'MW','Malawi');
insert  into pais(cd_pais, nr_pais, ds_pais) values (157,'MX','México');
insert  into pais(cd_pais, nr_pais, ds_pais) values (158,'MY','Malásia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (159,'MZ','Moçambique');
insert  into pais(cd_pais, nr_pais, ds_pais) values (160,'NA','Namíbia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (161,'NC','Nova Caledônia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (162,'NE','Níger');
insert  into pais(cd_pais, nr_pais, ds_pais) values (163,'NF','Ilha Norfolk');
insert  into pais(cd_pais, nr_pais, ds_pais) values (164,'NG','Nigéria');
insert  into pais(cd_pais, nr_pais, ds_pais) values (165,'NI','Nicarágua');
insert  into pais(cd_pais, nr_pais, ds_pais) values (166,'NL','Holanda');
insert  into pais(cd_pais, nr_pais, ds_pais) values (167,'NO','Noruega');
insert  into pais(cd_pais, nr_pais, ds_pais) values (168,'NP','Nepal');
insert  into pais(cd_pais, nr_pais, ds_pais) values (169,'NR','Nauru');
insert  into pais(cd_pais, nr_pais, ds_pais) values (170,'NU','Niue');
insert  into pais(cd_pais, nr_pais, ds_pais) values (171,'NZ','Nova Zelândia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (172,'OM','Omã');
insert  into pais(cd_pais, nr_pais, ds_pais) values (173,'PA','Panamá');
insert  into pais(cd_pais, nr_pais, ds_pais) values (174,'PE','Peru');
insert  into pais(cd_pais, nr_pais, ds_pais) values (175,'PF','Polinésia Francesa');
insert  into pais(cd_pais, nr_pais, ds_pais) values (176,'PG','Papua-Nova Guiné');
insert  into pais(cd_pais, nr_pais, ds_pais) values (177,'PH','Filipinas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (178,'PK','Paquistão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (179,'PL','Polônia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (180,'PM','Saint Pierre e Miquelon');
insert  into pais(cd_pais, nr_pais, ds_pais) values (181,'PN','Pitcairn');
insert  into pais(cd_pais, nr_pais, ds_pais) values (182,'PR','Porto Rico');
insert  into pais(cd_pais, nr_pais, ds_pais) values (183,'PS','Território da Palestina');
insert  into pais(cd_pais, nr_pais, ds_pais) values (184,'PT','Portugal');
insert  into pais(cd_pais, nr_pais, ds_pais) values (185,'PW','Palau');
insert  into pais(cd_pais, nr_pais, ds_pais) values (186,'PY','Paraguai');
insert  into pais(cd_pais, nr_pais, ds_pais) values (187,'QA','Catar');
insert  into pais(cd_pais, nr_pais, ds_pais) values (188,'RE','Reunião');
insert  into pais(cd_pais, nr_pais, ds_pais) values (189,'RO','Romênia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (190,'RS','Sérvia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (191,'RU','Rússia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (192,'RW','Ruanda');
insert  into pais(cd_pais, nr_pais, ds_pais) values (193,'SA','Arábia Saudita');
insert  into pais(cd_pais, nr_pais, ds_pais) values (194,'SB','Ilhas Salomão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (195,'SC','Seychelles');
insert  into pais(cd_pais, nr_pais, ds_pais) values (196,'SD','Sudão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (197,'SE','Suécia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (198,'SG','Cingapura');
insert  into pais(cd_pais, nr_pais, ds_pais) values (199,'SH','Santa Helena');
insert  into pais(cd_pais, nr_pais, ds_pais) values (200,'SI','Eslovênia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (201,'SJ','Svalbard e Jan Mayen');
insert  into pais(cd_pais, nr_pais, ds_pais) values (202,'SK','Eslováquia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (203,'SL','Serra Leoa');
insert  into pais(cd_pais, nr_pais, ds_pais) values (204,'SM','San Marino');
insert  into pais(cd_pais, nr_pais, ds_pais) values (205,'SN','Senegal');
insert  into pais(cd_pais, nr_pais, ds_pais) values (206,'SO','Somália');
insert  into pais(cd_pais, nr_pais, ds_pais) values (207,'SR','Suriname');
insert  into pais(cd_pais, nr_pais, ds_pais) values (208,'ST','São Tomé e Príncipe');
insert  into pais(cd_pais, nr_pais, ds_pais) values (209,'SV','El Salvador');
insert  into pais(cd_pais, nr_pais, ds_pais) values (210,'SY','Síria');
insert  into pais(cd_pais, nr_pais, ds_pais) values (211,'SZ','Suazilândia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (212,'TC','Ilhas Turks e Caicos');
insert  into pais(cd_pais, nr_pais, ds_pais) values (213,'TD','Chade');
insert  into pais(cd_pais, nr_pais, ds_pais) values (214,'TF','Territórios Franceses do Sul');
insert  into pais(cd_pais, nr_pais, ds_pais) values (215,'TG','Togo');
insert  into pais(cd_pais, nr_pais, ds_pais) values (216,'TH','Tailândia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (217,'TJ','Tadjiquistão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (218,'TK','Tokelau');
insert  into pais(cd_pais, nr_pais, ds_pais) values (219,'TL','Timor Leste');
insert  into pais(cd_pais, nr_pais, ds_pais) values (220,'TM','Turcomenistão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (221,'TN','Tunísia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (222,'TO','Tonga');
insert  into pais(cd_pais, nr_pais, ds_pais) values (223,'TR','Turquia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (224,'TT','Trinidad e Tobago');
insert  into pais(cd_pais, nr_pais, ds_pais) values (225,'TV','Tuvalu');
insert  into pais(cd_pais, nr_pais, ds_pais) values (226,'TW','Taiwan');
insert  into pais(cd_pais, nr_pais, ds_pais) values (227,'TZ','Tanzânia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (228,'UA','Ucrânia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (229,'UG','Uganda');
insert  into pais(cd_pais, nr_pais, ds_pais) values (230,'UM','Ilhas Menores Distantes dos Estados Unidos');
insert  into pais(cd_pais, nr_pais, ds_pais) values (231,'US','Estados Unidos');
insert  into pais(cd_pais, nr_pais, ds_pais) values (232,'UY','Uruguai');
insert  into pais(cd_pais, nr_pais, ds_pais) values (233,'UZ','Uzbequistão');
insert  into pais(cd_pais, nr_pais, ds_pais) values (234,'VA','Vaticano');
insert  into pais(cd_pais, nr_pais, ds_pais) values (235,'VC','São Vicente e Granadinas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (236,'VE','Venezuela');
insert  into pais(cd_pais, nr_pais, ds_pais) values (237,'VG','Ilhas Virgens Britânicas');
insert  into pais(cd_pais, nr_pais, ds_pais) values (238,'VI','Ilhas Virgens dos EUA');
insert  into pais(cd_pais, nr_pais, ds_pais) values (239,'VN','Vietnã');
insert  into pais(cd_pais, nr_pais, ds_pais) values (240,'VU','Vanuatu');
insert  into pais(cd_pais, nr_pais, ds_pais) values (241,'WF','Wallis e Futuna');
insert  into pais(cd_pais, nr_pais, ds_pais) values (242,'WS','Samoa');
insert  into pais(cd_pais, nr_pais, ds_pais) values (243,'YE','Iêmen');
insert  into pais(cd_pais, nr_pais, ds_pais) values (244,'YT','Mayotte');
insert  into pais(cd_pais, nr_pais, ds_pais) values (245,'ZA','África do Sul');
insert  into pais(cd_pais, nr_pais, ds_pais) values (246,'ZM','Zâmbia');
insert  into pais(cd_pais, nr_pais, ds_pais) values (247,'ZW','Zimbábue');
insert  into pais(cd_pais, nr_pais, ds_pais) values (248,'ZZ','Região desconhecida ou inválida');
